#!/bin/bash
while [[ $# -gt 0 ]]; do
    case "$1" in
        clean)
            read -p "autobuild: clean: Are you sure? [y/N]: " i
            if [[ "$i" == "Y" || "$i" == "y" ]]; then
                cd build
                rm -rf *
            elif [[ "$i" == "N" || "$i" == "n" || "$i" == "" ]]; then
                exit 0
            else
                echo "autobuild: Please enter Y or N"
                exit 1
            fi
        ;;
        build)
            cd build
            cmake -G Ninja ..
            ninja -C .
        ;;
        install)
            if [[ "$USER" != "root" ]]; then
                echo "Must be root"
                exit 1
            fi
            cp ./build/comet /usr/bin || cp ./comet /usr/bin
            cp ./build/cosmos /usr/bin || cp ./cosmos /usr/bin
        ;;
        *)
            echo "autobuild: Please specify one arg: clean, install, or build"
            exit 1
        ;;
    esac
    shift
done
